[loop]
token = "123"
channel_id = "ax133urt6ffaic6mgdy6br33jo"
admin_group_id = "6f13unqm4tff9moebxes8s4nqo"
duty_group_id = "6f13unqm4tff9moebxes8s4nqo"
server_url = "https://lemanapro.loop.ru"
team = "lemanapro"

[notification]
time = "08:50"
timezone = "Europe/Moscow"
reminder_interval_minutes = 15
weekends_alerts = true

[oncall]
token = "grafana-oncall-token"
base_url = "https://obs-grafana-oncall.example.com/138"
schedule_name = "Support"

[contacts.alice]
ldap = "alice.petrov"
full_name = "Алиса Петрова"
ldap_oncall = "12345678"

[contacts.bob]
ldap = "bob.ivanov"
full_name = "Боб Иванов"
ldap_oncall = "87654321"

[schedule]
monday = "alice"
tuesday = "alice"
wednesday = "bob"
thursday = "bob"
friday = "alice"
saturday = "bob"
sunday = "bob"
