[loop]
token = "123"
admin_group_id = "6f13unqm4tff9moebxes8s4nqo"
server_url = "https://lemanapro.loop.ru"
team = "lemanapro"

[notification]
time = "08:50"
timezone = "Europe/Moscow"
reminder_interval_minutes = 15

[contacts.alice]
ldap = "alice.petrov"
full_name = "Алиса Петрова"

[contacts.bob]
ldap = "bob.ivanov"
full_name = "Боб Иванов"

[schedule]
monday = "alice"
tuesday = "alice"
wednesday = "bob"
thursday = "bob"
friday = "alice"
saturday = "bob"
sunday = "bob"
