apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dutyscdp-bot.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "dutyscdp-bot.name" . }}
    helm.sh/chart: {{ include "dutyscdp-bot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

data:
  config.toml: |
{{- .Values.configToml | nindent 4 }}
