apiVersion: v1
kind: Service
metadata:
  name: {{ include "dutyscdp-bot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dutyscdp-bot.name" . }}
    helm.sh/chart: {{ include "dutyscdp-bot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "dutyscdp-bot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
